// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytijjjpvhhyubrknrtcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0aWpqanB2aGh5dWJya25ydGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzAwODAsImV4cCI6MjA2MzMwNjA4MH0.9lG8EqJ0wzSnQAGCuyNGZL-l7GNWbRlBXQzcJ8PjQ9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);